"""adding new column

Revision ID: 50794e57ab2f
Revises: 15d92f9e5c7c
Create Date: 2026-08-05 17:07:45.394727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50794e57ab2f'
down_revision: Union[str, Sequence[str], None] = '15d92f9e5c7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tabla Ususarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario')
    )
    with op.batch_alter_table('Tabla Carreras', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nombre'])

    with op.batch_alter_table('Tabla Estudiantes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Tabla Carreras', ['carrera'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Tabla Estudiantes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'Tabla_Carreras_vieja', ['carrera'], ['id'])

    with op.batch_alter_table('Tabla Carreras', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    op.drop_table('Tabla Ususarios')
    # ### end Alembic commands ###
