"""creacion de tablas iniciales

Revision ID: ac179e2cd8cf
Revises: 750af89f996e
Create Date: 2026-08-05 00:46:17.079768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac179e2cd8cf'
down_revision: Union[str, Sequence[str], None] = '750af89f996e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tabla Carreras', sa.Column('duracion_carrera', sa.String(), nullable=True))
    op.add_column('Tabla Carreras', sa.Column('numero_clases', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tabla Carreras', 'numero_clases')
    op.drop_column('Tabla Carreras', 'duracion_carrera')
    # ### end Alembic commands ###
