"""Crear tablas iniciales

Revision ID: b5c2945c925c
Revises: 
Create Date: 2026-08-06 01:18:17.234888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c2945c925c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Becas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_beca', sa.String(), nullable=True),
    sa.Column('porcentaje_descuento', sa.Float(), nullable=True),
    sa.Column('duracion', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Carreras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('duracion', sa.String(), nullable=True),
    sa.Column('cantidad_clases', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Clases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('creditos', sa.Integer(), nullable=True),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('modalidad', sa.String(), nullable=True),
    sa.Column('dia', sa.String(), nullable=True),
    sa.Column('horario', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Seguros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_seguro', sa.String(), nullable=True),
    sa.Column('porcentaje_descuento', sa.Float(), nullable=True),
    sa.Column('contrato', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('rol', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user')
    )
    op.create_table('Estudiantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('cuenta', sa.String(), nullable=True),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('estado_civil', sa.String(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('modalidad', sa.String(), nullable=True),
    sa.Column('id_beca', sa.Integer(), nullable=True),
    sa.Column('id_carrera', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_beca'], ['Becas.id'], ),
    sa.ForeignKeyConstraint(['id_carrera'], ['Carreras.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('cuenta')
    )
    op.create_table('Profesores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('estado_civil', sa.String(), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('modalidad', sa.String(), nullable=True),
    sa.Column('codigo_empleado', sa.String(), nullable=True),
    sa.Column('salario', sa.Float(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_empleado'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('RecursosHumanos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('correo', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('codigo_empleado', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['Usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_empleado'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('Inscripcion_Estudiante_Clase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_estudiante', sa.Integer(), nullable=True),
    sa.Column('id_clase', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_clase'], ['Clases.id'], ),
    sa.ForeignKeyConstraint(['id_estudiante'], ['Estudiantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Inscripcion_Profesor_Carrera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_profesor', sa.Integer(), nullable=True),
    sa.Column('id_carrera', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_carrera'], ['Carreras.id'], ),
    sa.ForeignKeyConstraint(['id_profesor'], ['Profesores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Inscripcion_Profesor_Clase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_profesor', sa.Integer(), nullable=True),
    sa.Column('id_clase', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_clase'], ['Clases.id'], ),
    sa.ForeignKeyConstraint(['id_profesor'], ['Profesores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Inscripcion_Profesor_Seguro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_profesor', sa.Integer(), nullable=True),
    sa.Column('id_seguro', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_profesor'], ['Profesores.id'], ),
    sa.ForeignKeyConstraint(['id_seguro'], ['Seguros.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Nomina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_profesor', sa.Integer(), nullable=True),
    sa.Column('id_rrhh', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_profesor'], ['Profesores.id'], ),
    sa.ForeignKeyConstraint(['id_rrhh'], ['RecursosHumanos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Nomina')
    op.drop_table('Inscripcion_Profesor_Seguro')
    op.drop_table('Inscripcion_Profesor_Clase')
    op.drop_table('Inscripcion_Profesor_Carrera')
    op.drop_table('Inscripcion_Estudiante_Clase')
    op.drop_table('RecursosHumanos')
    op.drop_table('Profesores')
    op.drop_table('Estudiantes')
    op.drop_table('Usuarios')
    op.drop_table('Seguros')
    op.drop_table('Clases')
    op.drop_table('Carreras')
    op.drop_table('Becas')
    # ### end Alembic commands ###
